version: '3.9'
services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    privileged: true
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    container_name: nearby_db
    image: "mongo"
    ports:
      - 27017:27017